### ISSUE TITLE
Change repository URL

### ISSUE THREAD

**Issue by maelle** [lucarraro/traudem#36]
to https://lucarraro.github.io/traudem/ in

![image](https://user-images.githubusercontent.com/8360597/195099645-a597f34d-a306-4d46-856b-ea1f683987f9.png)

I will fix other links, but I don't have access to this setting. :smile_cat:

**Comment by lucarraro** [comment]
Hi, sorry but I didn't understand whether I actually need to do something here...

**Comment by maelle** [comment]
Thank you!
