### ISSUE TITLE
add alternative text + caption for vignette and README chunks

### ISSUE THREAD

**Issue by maelle** [lucarraro/traudem#39]

**Comment by maelle** [comment]
@lucarraro Could you please make the placeholder alternative text I added, more informative? The two lines are

https://github.com/lucarraro/traudem/blob/97b36957f8c150c8c92b86f7e3a6da9544efb578/man/fragments/_example.Rmd#L14

and 

https://github.com/lucarraro/traudem/blob/97b36957f8c150c8c92b86f7e3a6da9544efb578/man/fragments/_example.Rmd#L103

Here's an useful link https://axesslab.com/alt-texts/ (I lack domain expertise to describe these two plots)

**Comment by lucarraro** [comment]
done

**Comment by maelle** [comment]
Awesome :rocket:
