### ISSUE TITLE
Test installation instructions

### ISSUE THREAD

**Issue by maelle** [lucarraro/traudem#6]
- Install this package (using pak for instance).
- Read and follow https://cynkra.github.io/traudem/articles/taudem-installation.html
- Write down anything that is unclear or leads to an error message.
- Comment here with the output of `traudem::taudem_sitrep()` as well as your operating system.

**Comment by maelle** [comment]
@wael-sadek so it worked, even with the latest MPI version? On my machine only my branch more-mpi-deprecations work.

Upstream, "Develop" seems to be the default branch.

**Comment by maelle** [comment]
New link to vignette https://cynkra.github.io/traudem/articles/taudem-installation.html

**Comment by pat-s** [comment]
Using https://github.com/maelle/TauDEM/tree/more-mpi-deprecations worked!

```r
 traudem::taudem_sitrep()
✔ Found GDAL version 3.5.2.
✔ Found mpiexec (OpenRTE) 4.1.4 (MPI).
✔ Found TauDEM path (/usr/local/taudem).
✔ Found TauDEM executables directory (/usr/local/taudem).
✔ Found all TauDEM executables.
ℹ Testing TauDEM on an example file...
── TauDEM output ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

PitRemove version 5.3.9
Input file MED_01_01.tif has projected coordinate system.
Nodata value input to create partition from file: -340282299999999994960115009090224128000.000000
Nodata value recast to float used in partition raster: -340282306073709652508363335590014353408.000000
Processes: 1
Header read time: 0.035282
Data read time: 0.003173
Compute time: 0.143207
Write time: 0.014782
Total time: 0.196444
This run may take on the order of 1 minutes to complete.
This estimate is very approximate. 
Run time is highly uncertain as it depends on the complexity of the input data 
and speed and memory of the computer. This estimate is based on our testing on 
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
── End of TauDEM output ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔ Was able to launch a TauDEM example!
! Make sure you see no serious error message above.
```

Suggestion: Give a hint how long the process running the example might take, e.g. something like 

> ℹ Testing TauDEM on an example file...(might take XXX min to complete). During my first run, I was waiting at this line and the "This run may take on the order of 1 minutes to complete." appeared only afterwars.

Good work! 💪️

**Comment by maelle** [comment]
Thanks a ton @pat-s!

* Good idea.
* Regarding the cache sadly I have no idea as it's not documented :sweat_smile: But I'll definitely keep this in mind.

**Comment by wael-sadek** [comment]
@maelle , Just tested it in Windows.
It's complaining that `Can't find MPI`
Please note that `--version`  does not exist in windows for `mpiexec`. That's why it's failing I guess.

**Comment by maelle** [comment]
Thank you!! How could I print the version for MPI on Windows?

**Comment by wael-sadek** [comment]
> Thank you!! How could I print the version for MPI on Windows?

You can't 😅 

Below are all the available options for mpich, the version is on the first line.

```
C:\Users\Wael\traudem>mpiexec
Microsoft MPI Startup Program [Version 10.1.12498.18]

Launches an application on multiple hosts.

Usage:

    mpiexec [options] executable [args] [ : [options] exe [args] : ... ]
    mpiexec -configfile <file name>

Common options:

-n <num_processes>
-env <env_var_name> <env_var_value>
-wdir <working_directory>
-hosts n host1 [m1] host2 [m2] ... hostn [mn]
-cores <num_cores_per_host>
-lines
-debug [0-3]
-logfile <log file>

Examples:

    mpiexec -n 4 pi.exe
    mpiexec -hosts 1 server1 master : -n 8 worker

For a complete list of options, run mpiexec -help2
For a list of environment variables, run mpiexec -help3

You can reach the Microsoft MPI team via email at askmpi@microsoft.com
```

**Comment by maelle** [comment]
Ok, thanks, I'll push a fix!

**Comment by wael-sadek** [comment]
> @wael-sadek so it worked, even with the latest MPI version? On my machine only my branch more-mpi-deprecations work.
> 
> Upstream, "Develop" seems to be the default branch.

Yes, it works. It's used in the workflow.

**Comment by maelle** [comment]
I do not understand why it works on GitHub Actions but not on my machine nor on @pat-s' machine. I suppose it's due to the MPI version :thinking:
